backend:
  name: github
  repo: xovucom/webdesignfla
  auth_type: oauth
  base_url: https://api.decapcms.org
  auth_endpoint: auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }