backend:
  name: github
  repo: xovucom/webdesignfla # Your repository
  auth_type: oauth
  base_url: https://webdesignfla.vercel.app # Your site's URL
  auth_endpoint: /api/auth # The path to the file you just created

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }